"""Contains llm response class implementation."""

from __future__ import annotations

import time

from pydantic import BaseModel, Field

from .chat_message import AssistantChatMessage


class LLMResponse(BaseModel):
    """Large language model response type implementation.

    Attributes
    ----------
    content : str
        llm response content message.
    num_tokens : int
        number tokens generated.
    model_name : str
        name of model.
    """

    content: str
    num_tokens: int
    model_name: str
    timestamp: float = Field(default_factory=time.time)

    def get_content(self) -> str:
        """Get content generated by llm.

        Returns
        -------
        str
            content generated by llm.
        """
        return self.content

    def get_num_tokens(self) -> int:
        """Get number of tokens generated by llm.

        Returns
        -------
        int
            number of tokens generated by llm.
        """
        return self.num_tokens

    def get_model_name(self) -> str:
        """Get name of the llm model used for inference.

        Returns
        -------
        str
            name of llm model used for inference tokens.
        """
        return self.model_name

    def to_chat_message(self, rating: float = 1.0) -> AssistantChatMessage:
        """Transform llm response to assistant chat message.

        Parameters
        ----------
        rating : float
            rating to set.
            Default is 1.0.

        Returns
        -------
        AssistantChatMessage
            assistant chat message corresponding to
            llm response.
        """
        return AssistantChatMessage(timestamp=self.timestamp, text=self.content, rating=rating)
